#!/bin/bash

if [ $# -lt 2 ]; then
	echo "Usage: $0 <file> <length> [debug(-d)]" >&2
	exit 1
fi

if find src -type f -newer target | grep -q .; then
    mvn install
    status=$?
else
	status=0
fi

if [ "$status" -ne 0 ]; then
	exit "$status"
fi

java -cp target/string-constraint-solvers-1.0-SNAPSHOT-jar-with-dependencies.jar edu.boisestate.cs.SolveMain "$1" -s inverse -v 2 -l "$2" $3